# Generated by Django 4.1.2 on 2022-12-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Traveler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("password", models.CharField(max_length=50)),
                ("user_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TravelersPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_date", models.DateField()),
                ("arrival_date", models.DateField()),
                ("destination_country", models.CharField(max_length=50)),
                ("origin_country", models.CharField(max_length=50)),
                ("passport_no", models.IntegerField()),
                ("ticket_no", models.IntegerField()),
                ("airlines_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("contact_no", models.IntegerField()),
            ],
        ),
    ]
