# Generated by Django 4.1.2 on 2022-11-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Traveler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
